### ISSUE TITLE
Discrepancy in Aerospike Configuration

### ISSUE THREAD

**Issue by PrajayVK** [aerospike/spring-data-aerospike#850]
Snippet 1 (Documentation) - Application.properties file
```
spring.data.aerospike.scans-enabled=false
spring.data.aerospike.send-key=true
spring.data.aerospike.create-indexes-on-startup=true
spring.data.aerospike.index-cache-refresh-seconds=3600
spring.data.aerospike.server-version-refresh-seconds=3600
spring.data.aerospike.query-max-records=10000
spring.data.aerospike.batch-write-size=100
spring.data.aerospike.keep-original-key-types=false
```

Snippet 2 - Application.yml file

```
spring:
  application:
    name: application-name
  lifecycle:
    timeout-per-shutdown-phase: 20s
  data:
    aerospike:
      username: admin
      password: admin
      namespace: test
      host: localhost
      port: 3000
      batch-write-size: 100
      create-indexes-on-startup: true
      index-cache-refresh-seconds: 3600
      keep-original-key-types: false
      query-max-records: 10000
      server-version-refresh-seconds: 3600
      scans-enabled: false
```
When I use Snippet 2 in my code it doesn't work which is an exact replica of the documentation I got, refer Snippet 1  

Snippet 3 -

```
spring:
  application:
    name: application-name
  lifecycle:
    timeout-per-shutdown-phase: 20s
  data:
    aerospike:
      username: admin
      password: admin
      namespace: test
      host: localhost
      port: 3000
      batchWriteSize: 100
      createIndexesOnStartup: false # we are not using @indexed annotation and manually creating indexes
      indexCacheRefreshSeconds: 3600
      keepOriginalKeyTypes: false
      queryMaxRecords: 10000
      serverVersionRefreshSeconds: 3600
      scansEnabled: false
```

Using Snippet 2 doesn't work so while trying out all the possibilities Snippet 3 worked. 
Is there any difference between declaring the properties in application.properties (Snipper 1) and application.yml (Snippet 2)
I have used spring-data-aerospike 5.0.0 and as per the documentation I have mentioned the properties. It could be an issue with how config is read with utils class and spring boot yaml

 Am I doing something wrong or missing something?

**Comment by agrgr** [comment]
Hello @PrajayVK,

Do you have a sample repository where the issue gets reproduced?
Here is a link to a working [example](https://github.com/agrgr/simple-springboot-aerospike-demo) that successfully uses application.yml:

```
### Application.yml
spring:
  aerospike:
    hosts: localhost:3000
  data:
    aerospike:
      namespace: test
      batch-write-size: 100
      create-indexes-on-startup: true
      index-cache-refresh-seconds: 3600
      keep-original-key-types: false
      query-max-records: 10
      server-version-refresh-seconds: 3600
      scans-enabled: false
```
