### ISSUE TITLE
spring.aerospike.hosts does not configure hosts correctly.

### ISSUE THREAD

**Issue by swapy** [aerospike/spring-data-aerospike#851]
I am using spring data aerospike 5.0.0

I am using yaml configuration.

I set 
`spring.aerospike.hosts=somehost:5000,someother:6000`

```yaml
spring:
   aerospike:
      hosts: somehost:5000,someother:6000
```

But this always results in exception as it tries to connect to localhost 3000

I think this is bug in spring data aerospike.

I tried with environment variables too.
